In [2]:
import pandas as pd

In [1]:
import pandas as pd

data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Divya"],
    "Department": ["CSE", "ECE", "CSE", "ECE", "CSE", "ECE"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "Marks": [80, 90, 70, 85, 95, 75],
    "Attendance": [85, 90, 80, 95, 88, 92]
}

df = pd.DataFrame(data)

print(df)

    Name Department  Gender  Marks  Attendance
0   Ravi        CSE    Male     80          85
1  Priya        ECE  Female     90          90
2   Arun        CSE    Male     70          80
3  Sneha        ECE  Female     85          95
4  Kiran        CSE    Male     95          88
5  Divya        ECE  Female     75          92

In [3]:
print(df.groupby("Department").groups)

{'CSE': [0, 2, 4], 'ECE': [1, 3, 5]}

In [4]:
for department, group in df.groupby("Department"):
    print("\nDepartment:", department)
    print(group)

Department: CSE
    Name Department Gender  Marks  Attendance
0   Ravi        CSE   Male     80          85
2   Arun        CSE   Male     70          80
4  Kiran        CSE   Male     95          88

Department: ECE
    Name Department  Gender  Marks  Attendance
1  Priya        ECE  Female     90          90
3  Sneha        ECE  Female     85          95
5  Divya        ECE  Female     75          92

In [5]:
print(df.groupby("Department")["Marks"].sum())

Department
CSE    245
ECE    250
Name: Marks, dtype: int64

In [6]:
print(df.groupby("Department")["Marks"].mean())

Department
CSE    81.666667
ECE    83.333333
Name: Marks, dtype: float64

In [7]:
print(df.groupby("Department")["Name"].count())

Department
CSE    3
ECE    3
Name: Name, dtype: int64

In [8]:
print(df.groupby("Department")["Marks"].min())

Department
CSE    70
ECE    75
Name: Marks, dtype: int64

In [9]:
print(df.groupby("Department")["Marks"].max())

Department
CSE    95
ECE    90
Name: Marks, dtype: int64

In [10]:
result = df.groupby("Department")["Marks"].agg(
    ["sum", "mean", "count", "min", "max"]
)

print(result)

            sum       mean  count  min  max
Department
CSE         245  81.666667      3   70   95
ECE         250  83.333333      3   75   90

In [11]:
result = df.groupby(
    ["Department", "Gender"]
)["Marks"].mean()

print(result)

Department  Gender
CSE         Male      81.666667
ECE         Female    83.333333
Name: Marks, dtype: float64

In [12]:
print(
    df.groupby("Department")[["Marks", "Attendance"]].mean()
)

                Marks  Attendance
Department
CSE         81.666667   84.333333
ECE         83.333333   92.333333

In [14]:
result = df.groupby(
    ["Department", "Gender"]
)["Marks"].mean()

print(result)

Department  Gender
CSE         Male      81.666667
ECE         Female    83.333333
Name: Marks, dtype: float64

In [16]:
print(df.columns)

Index(['Name', 'Department', 'Gender', 'Marks', 'Attendance'], dtype='object')

In [17]:
df.groupby("Department")["Marks"].sum()

Department
CSE    245
ECE    250
Name: Marks, dtype: int64

In [18]:
# Total marks
print(df.groupby("Department")["Marks"].sum())

# Average marks
print(df.groupby("Department")["Marks"].mean())

# Count students
print(df.groupby("Department")["Name"].count())

# Minimum marks
print(df.groupby("Department")["Marks"].min())

# Maximum marks
print(df.groupby("Department")["Marks"].max())

Department
CSE    245
ECE    250
Name: Marks, dtype: int64
Department
CSE    81.666667
ECE    83.333333
Name: Marks, dtype: float64
Department
CSE    3
ECE    3
Name: Name, dtype: int64
Department
CSE    70
ECE    75
Name: Marks, dtype: int64
Department
CSE    95
ECE    90
Name: Marks, dtype: int64

In [19]:

import pandas as pd

# Create sample data
data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Divya"],
    "Department": ["CSE", "ECE", "CSE", "ECE", "CSE", "ECE"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "Marks": [80, 90, 70, 85, 95, 75],
    "Attendance": [85, 90, 80, 95, 88, 92]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

print("\n1. Total Marks:")
print(df.groupby("Department")["Marks"].sum())

print("\n2. Average Marks:")
print(df.groupby("Department")["Marks"].mean())

print("\n3. Student Count:")
print(df.groupby("Department")["Name"].count())

print("\n4. Minimum Marks:")
print(df.groupby("Department")["Marks"].min())

print("\n5. Maximum Marks:")
print(df.groupby("Department")["Marks"].max())

print("\n6. All Statistics:")
print(df.groupby("Department")["Marks"].agg(
    ["sum", "mean", "count", "min", "max"]
))

print("\n7. Group by Department and Gender:")
print(df.groupby(["Department", "Gender"])["Marks"].mean())

print("\n8. Average Marks and Attendance:")
print(df.groupby("Department")[["Marks", "Attendance"]].mean())

Original Dataset:
    Name Department  Gender  Marks  Attendance
0   Ravi        CSE    Male     80          85
1  Priya        ECE  Female     90          90
2   Arun        CSE    Male     70          80
3  Sneha        ECE  Female     85          95
4  Kiran        CSE    Male     95          88
5  Divya        ECE  Female     75          92

1. Total Marks:
Department
CSE    245
ECE    250
Name: Marks, dtype: int64

2. Average Marks:
Department
CSE    81.666667
ECE    83.333333
Name: Marks, dtype: float64

3. Student Count:
Department
CSE    3
ECE    3
Name: Name, dtype: int64

4. Minimum Marks:
Department
CSE    70
ECE    75
Name: Marks, dtype: int64

5. Maximum Marks:
Department
CSE    95
ECE    90
Name: Marks, dtype: int64

6. All Statistics:
            sum       mean  count  min  max
Department
CSE         245  81.666667      3   70   95
ECE         250  83.333333      3   75   90

7. Group by Department and Gender:
Department  Gender
CSE         Male      81.666667
ECE         Female    83.333333
Name: Marks, dtype: float64

8. Average Marks and Attendance:
                Marks  Attendance
Department
CSE         81.666667   84.333333
ECE         83.333333   92.333333

In [20]:
df.groupby(["Department", "Gender"])["Marks"].mean()

Department  Gender
CSE         Male      81.666667
ECE         Female    83.333333
Name: Marks, dtype: float64